import type { Language } from "@/lib/languages";

export type MyBooksLabels = {
  techError: string;
  rateLimited: string;
  somethingWrong: string;
  booksFound: string; // "{n}"
  purchaseSuccessToast: string;
  paymentProcessingToast: string;
  purchaseReadyToast: string;
  downloadStarted: string;
  bookReady: string;
  waDelivered: string;
  downloading: string;
  linkPreparing: string;
  libraryTitle: string;
  librarySub: string;
  phonePlaceholder: string;
  searchBtn: string;
  searchYourBooks: string;
  searchPrompt: string;
  booksCount: string; // "{n}"
  noBooksFound: string;
  checkNumber: string;
  paidButNoBook: string;
  suggestedForYou: string;
  needHelp: string;
  callCta: string;
  whatsappHelpCta: string;
  waMyPdf: string;
  waLinkNote: string;
  waLinkNoteExpire: string;
  waHelpRequest: string;
  waPaidNoBook: string; // "{phone}"
};

export const MYBOOKS_LABELS: Record<Language, MyBooksLabels> = {
  MARATHI: {
    techError: "तांत्रिक अडचण आली. कृपया थोड्या वेळाने प्रयत्न करा.",
    rateLimited: "खूप जास्त वेळा प्रयत्न केले गेले आहेत. कृपया थोड्या वेळाने प्रयत्न करा.",
    somethingWrong: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
    booksFound: "{n} पुस्तके सापडली!",
    purchaseSuccessToast: "खरेदी यशस्वी! तुमचे पुस्तक खालील आहे.",
    paymentProcessingToast: "पेमेंट प्रक्रियेत आहे... कृपया थांबा.",
    purchaseReadyToast: "खरेदी यशस्वी! तुमचे पुस्तक तयार आहे.",
    downloadStarted: "डाउनलोड सुरू झाले! 📥",
    bookReady: "तुमचे पुस्तक तयार आहे — आता डाउनलोड करा",
    waDelivered: "तुमच्या WhatsApp वर PDF पाठवली आहे. न मिळाल्यास खालील बटन वापरा.",
    downloading: "डाउनलोड होत आहे...",
    linkPreparing: "तुमची लिंक तयार होत आहे...",
    libraryTitle: "तुमची डिजिटल लायब्ररी",
    librarySub: "WhatsApp नंबर टाका — तुमची पुस्तके लगेच मिळवा",
    phonePlaceholder: "WhatsApp नंबर...",
    searchBtn: "शोधा",
    searchYourBooks: "तुमची पुस्तके शोधा",
    searchPrompt: "वर तुमचा WhatsApp नंबर टाकून \"शोधा\" दाबा",
    booksCount: "{n} पुस्तके",
    noBooksFound: "पुस्तके सापडली नाहीत",
    checkNumber: "नंबर तपासा किंवा सपोर्टशी संपर्क करा.",
    paidButNoBook: "पैसे भरले पण पुस्तक नाही?",
    suggestedForYou: "तुमच्यासाठी सुचवलेले",
    needHelp: "मदत हवी? आम्ही येथे आहोत.",
    callCta: "कॉल करा",
    whatsappHelpCta: "WhatsApp वर मदत घ्या",
    waMyPdf: "वकिली आणि कायदे — माझी PDF",
    waLinkNote: "हा link फक्त माझ्यासाठी आहे. हे message save करा.",
    waLinkNoteExpire: "हा link फक्त माझ्यासाठी आहे. हे message save करा — link expire होण्यापूर्वी.",
    waHelpRequest: "नमस्कार 🙏 वकिली आणि कायदे टीम,\nमला माझी पुस्तके डाऊनलोड करताना मदत हवी आहे. कृपया मार्गदर्शन करा.",
    waPaidNoBook: "नमस्कार 🙏 वकिली आणि कायदे टीम,\nमी पुस्तकाचे पैसे भरले आहेत, पण ते माझ्या खात्यात दिसत नाही.\n📱 माझा नंबर: {phone}\nकृपया तपासा.",
  },
  HINDI: {
    techError: "तकनीकी समस्या हुई। कृपया थोड़ी देर बाद प्रयास करें।",
    rateLimited: "बहुत अधिक बार प्रयास किया गया है। कृपया थोड़ी देर बाद प्रयास करें।",
    somethingWrong: "कुछ गलत हुआ। कृपया पुनः प्रयास करें।",
    booksFound: "{n} किताबें मिलीं!",
    purchaseSuccessToast: "खरीद सफल! आपकी किताब नीचे है।",
    paymentProcessingToast: "भुगतान प्रक्रिया में है... कृपया प्रतीक्षा करें।",
    purchaseReadyToast: "खरीद सफल! आपकी किताब तैयार है।",
    downloadStarted: "डाउनलोड शुरू हुआ! 📥",
    bookReady: "आपकी किताब तैयार है — अभी डाउनलोड करें",
    waDelivered: "आपके WhatsApp पर PDF भेजी गई है। न मिलने पर नीचे बटन का उपयोग करें।",
    downloading: "डाउनलोड हो रहा है...",
    linkPreparing: "आपकी लिंक तैयार हो रही है...",
    libraryTitle: "आपकी डिजिटल लाइब्रेरी",
    librarySub: "WhatsApp नंबर डालें — अपनी किताबें तुरंत पाएं",
    phonePlaceholder: "WhatsApp नंबर...",
    searchBtn: "खोजें",
    searchYourBooks: "अपनी किताबें खोजें",
    searchPrompt: "ऊपर अपना WhatsApp नंबर डालकर \"खोजें\" दबाएं",
    booksCount: "{n} किताबें",
    noBooksFound: "किताबें नहीं मिलीं",
    checkNumber: "नंबर जांचें या सपोर्ट से संपर्क करें।",
    paidButNoBook: "पैसे भरे पर किताब नहीं?",
    suggestedForYou: "आपके लिए सुझाए गए",
    needHelp: "मदद चाहिए? हम यहां हैं।",
    callCta: "कॉल करें",
    whatsappHelpCta: "WhatsApp पर मदद लें",
    waMyPdf: "वकिली आणि कायदे — मेरी PDF",
    waLinkNote: "यह link सिर्फ मेरे लिए है। यह message save करें।",
    waLinkNoteExpire: "यह link सिर्फ मेरे लिए है। यह message save करें — link expire होने से पहले।",
    waHelpRequest: "नमस्कार 🙏 वकिली आणि कायदे टीम,\nमुझे अपनी किताबें डाउनलोड करने में मदद चाहिए। कृपया मार्गदर्शन करें।",
    waPaidNoBook: "नमस्कार 🙏 वकिली आणि कायदे टीम,\nमैंने किताब के पैसे भर दिए हैं, पर वह मेरे खाते में नहीं दिख रही।\n📱 मेरा नंबर: {phone}\nकृपया जांचें।",
  },
  ENGLISH: {
    techError: "A technical issue occurred. Please try again shortly.",
    rateLimited: "Too many attempts. Please try again shortly.",
    somethingWrong: "Something went wrong. Please try again.",
    booksFound: "{n} books found!",
    purchaseSuccessToast: "Purchase successful! Your book is below.",
    paymentProcessingToast: "Payment is processing... please wait.",
    purchaseReadyToast: "Purchase successful! Your book is ready.",
    downloadStarted: "Download started! 📥",
    bookReady: "Your book is ready — download now",
    waDelivered: "The PDF has been sent to your WhatsApp. If not received, use the button below.",
    downloading: "Downloading...",
    linkPreparing: "Your link is being prepared...",
    libraryTitle: "Your Digital Library",
    librarySub: "Enter your WhatsApp number — get your books instantly",
    phonePlaceholder: "WhatsApp number...",
    searchBtn: "Search",
    searchYourBooks: "Find your books",
    searchPrompt: "Enter your WhatsApp number above and tap \"Search\"",
    booksCount: "{n} books",
    noBooksFound: "No books found",
    checkNumber: "Check the number or contact support.",
    paidButNoBook: "Paid but no book?",
    suggestedForYou: "Suggested for you",
    needHelp: "Need help? We're here.",
    callCta: "Call us",
    whatsappHelpCta: "Get help on WhatsApp",
    waMyPdf: "Vakili Aani Kayde — My PDF",
    waLinkNote: "This link is only for me. Save this message.",
    waLinkNoteExpire: "This link is only for me. Save this message before the link expires.",
    waHelpRequest: "Hello 🙏 Vakili Aani Kayde team,\nI need help downloading my books. Please guide me.",
    waPaidNoBook: "Hello 🙏 Vakili Aani Kayde team,\nI have paid for the book, but it's not showing in my account.\n📱 My number: {phone}\nPlease check.",
  },
  TAMIL: {
    techError: "தொழில்நுட்பச் சிக்கல் ஏற்பட்டது. சிறிது நேரம் கழித்து முயற்சிக்கவும்.",
    rateLimited: "மிக அதிக முறை முயற்சித்துவிட்டீர்கள். சிறிது நேரம் கழித்து முயற்சிக்கவும்.",
    somethingWrong: "ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
    booksFound: "{n} புத்தகங்கள் கிடைத்தன!",
    purchaseSuccessToast: "வாங்குதல் வெற்றி! உங்கள் புத்தகம் கீழே உள்ளது.",
    paymentProcessingToast: "பணம் செயலாக்கத்தில் உள்ளது... காத்திருக்கவும்.",
    purchaseReadyToast: "வாங்குதல் வெற்றி! உங்கள் புத்தகம் தயாராக உள்ளது.",
    downloadStarted: "பதிவிறக்கம் தொடங்கியது! 📥",
    bookReady: "உங்கள் புத்தகம் தயார் — இப்போது பதிவிறக்கவும்",
    waDelivered: "உங்கள் WhatsApp-இல் PDF அனுப்பப்பட்டது. கிடைக்கவில்லை எனில் கீழே உள்ள பொத்தானைப் பயன்படுத்தவும்.",
    downloading: "பதிவிறக்குகிறது...",
    linkPreparing: "உங்கள் இணைப்பு தயாராகிறது...",
    libraryTitle: "உங்கள் டிஜிட்டல் நூலகம்",
    librarySub: "WhatsApp எண்ணை உள்ளிடவும் — உங்கள் புத்தகங்களை உடனே பெறுங்கள்",
    phonePlaceholder: "WhatsApp எண்...",
    searchBtn: "தேடு",
    searchYourBooks: "உங்கள் புத்தகங்களைத் தேடுங்கள்",
    searchPrompt: "மேலே உங்கள் WhatsApp எண்ணை உள்ளிட்டு \"தேடு\" அழுத்தவும்",
    booksCount: "{n} புத்தகங்கள்",
    noBooksFound: "புத்தகங்கள் கிடைக்கவில்லை",
    checkNumber: "எண்ணைச் சரிபார்க்கவும் அல்லது ஆதரவைத் தொடர்பு கொள்ளவும்.",
    paidButNoBook: "பணம் செலுத்தியும் புத்தகம் இல்லையா?",
    suggestedForYou: "உங்களுக்காக பரிந்துரைக்கப்பட்டவை",
    needHelp: "உதவி தேவையா? நாங்கள் இங்கே இருக்கிறோம்.",
    callCta: "அழைக்கவும்",
    whatsappHelpCta: "WhatsApp-இல் உதவி பெறுங்கள்",
    waMyPdf: "வகிலி ஆணி காயதே — என் PDF",
    waLinkNote: "இந்த link என்னுக்கானது மட்டுமே. இந்த message-ஐ save செய்யவும்.",
    waLinkNoteExpire: "இந்த link என்னுக்கானது மட்டுமே. இந்த message-ஐ save செய்யவும் — link expire ஆகும் முன்.",
    waHelpRequest: "வணக்கம் 🙏 வகிலி ஆணி காயதே குழு,\nஎன் புத்தகங்களைப் பதிவிறக்க உதவி தேவை. தயவுசெய்து வழிகாட்டவும்.",
    waPaidNoBook: "வணக்கம் 🙏 வகிலி ஆணி காயதே குழு,\nநான் புத்தகத்திற்குப் பணம் செலுத்திவிட்டேன், ஆனால் அது என் கணக்கில் தெரியவில்லை.\n📱 என் எண்: {phone}\nதயவுசெய்து சரிபார்க்கவும்.",
  },
  TELUGU: {
    techError: "సాంకేతిక సమస్య ఏర్పడింది. దయచేసి కొద్దిసేపటి తర్వాత ప్రయత్నించండి.",
    rateLimited: "చాలాసార్లు ప్రయత్నించారు. దయచేసి కొద్దిసేపటి తర్వాత ప్రయత్నించండి.",
    somethingWrong: "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    booksFound: "{n} పుస్తకాలు దొరికాయి!",
    purchaseSuccessToast: "కొనుగోలు విజయవంతం! మీ పుస్తకం క్రింద ఉంది.",
    paymentProcessingToast: "చెల్లింపు ప్రాసెస్‌లో ఉంది... దయచేసి వేచి ఉండండి.",
    purchaseReadyToast: "కొనుగోలు విజయవంతం! మీ పుస్తకం సిద్ధంగా ఉంది.",
    downloadStarted: "డౌన్‌లోడ్ ప్రారంభమైంది! 📥",
    bookReady: "మీ పుస్తకం సిద్ధంగా ఉంది — ఇప్పుడే డౌన్‌లోడ్ చేయండి",
    waDelivered: "మీ WhatsApp కు PDF పంపబడింది. అందకపోతే క్రింది బటన్ ఉపయోగించండి.",
    downloading: "డౌన్‌లోడ్ అవుతోంది...",
    linkPreparing: "మీ లింక్ సిద్ధమవుతోంది...",
    libraryTitle: "మీ డిజిటల్ లైబ్రరీ",
    librarySub: "WhatsApp నంబర్ నమోదు చేయండి — మీ పుస్తకాలను వెంటనే పొందండి",
    phonePlaceholder: "WhatsApp నంబర్...",
    searchBtn: "వెతకండి",
    searchYourBooks: "మీ పుస్తకాలను వెతకండి",
    searchPrompt: "పైన మీ WhatsApp నంబర్ నమోదు చేసి \"వెతకండి\" నొక్కండి",
    booksCount: "{n} పుస్తకాలు",
    noBooksFound: "పుస్తకాలు దొరకలేదు",
    checkNumber: "నంబర్‌ను తనిఖీ చేయండి లేదా సపోర్ట్‌ను సంప్రదించండి.",
    paidButNoBook: "డబ్బు చెల్లించారా కానీ పుస్తకం లేదా?",
    suggestedForYou: "మీ కోసం సూచించబడినవి",
    needHelp: "సహాయం కావాలా? మేము ఇక్కడ ఉన్నాము.",
    callCta: "కాల్ చేయండి",
    whatsappHelpCta: "WhatsApp లో సహాయం పొందండి",
    waMyPdf: "వకిలి ఆణి కాయదే — నా PDF",
    waLinkNote: "ఈ link నా కోసం మాత్రమే. ఈ message ను save చేయండి.",
    waLinkNoteExpire: "ఈ link నా కోసం మాత్రమే. ఈ message ను save చేయండి — link expire అయ్యే ముందు.",
    waHelpRequest: "నమస్కారం 🙏 వకిలి ఆణి కాయదే టీమ్,\nనా పుస్తకాలను డౌన్‌లోడ్ చేయడంలో సహాయం కావాలి. దయచేసి మార్గనిర్దేశం చేయండి.",
    waPaidNoBook: "నమస్కారం 🙏 వకిలి ఆణి కాయదే టీమ్,\nనేను పుస్తకానికి డబ్బు చెల్లించాను, కానీ అది నా ఖాతాలో కనిపించడం లేదు.\n📱 నా నంబర్: {phone}\nదయచేసి తనిఖీ చేయండి.",
  },
  GUJARATI: {
    techError: "ટેકનિકલ સમસ્યા આવી. કૃપા કરીને થોડી વાર પછી પ્રયાસ કરો.",
    rateLimited: "ઘણી વાર પ્રયાસ કરવામાં આવ્યો છે. કૃપા કરીને થોડી વાર પછી પ્રયાસ કરો.",
    somethingWrong: "કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો.",
    booksFound: "{n} પુસ્તકો મળ્યાં!",
    purchaseSuccessToast: "ખરીદી સફળ! તમારું પુસ્તક નીચે છે.",
    paymentProcessingToast: "ચુકવણી પ્રક્રિયામાં છે... કૃપા કરીને રાહ જુઓ.",
    purchaseReadyToast: "ખરીદી સફળ! તમારું પુસ્તક તૈયાર છે.",
    downloadStarted: "ડાઉનલોડ શરૂ થયું! 📥",
    bookReady: "તમારું પુસ્તક તૈયાર છે — હમણાં ડાઉનલોડ કરો",
    waDelivered: "તમારા WhatsApp પર PDF મોકલવામાં આવી છે. ન મળે તો નીચેનું બટન વાપરો.",
    downloading: "ડાઉનલોડ થઈ રહ્યું છે...",
    linkPreparing: "તમારી લિંક તૈયાર થઈ રહી છે...",
    libraryTitle: "તમારી ડિજિટલ લાઇબ્રેરી",
    librarySub: "WhatsApp નંબર દાખલ કરો — તમારી પુસ્તકો તરત જ મેળવો",
    phonePlaceholder: "WhatsApp નંબર...",
    searchBtn: "શોધો",
    searchYourBooks: "તમારી પુસ્તકો શોધો",
    searchPrompt: "ઉપર તમારો WhatsApp નંબર દાખલ કરીને \"શોધો\" દબાવો",
    booksCount: "{n} પુસ્તકો",
    noBooksFound: "પુસ્તકો મળ્યાં નથી",
    checkNumber: "નંબર તપાસો અથવા સપોર્ટનો સંપર્ક કરો.",
    paidButNoBook: "પૈસા ભર્યા પણ પુસ્તક નથી?",
    suggestedForYou: "તમારા માટે સૂચવેલ",
    needHelp: "મદદ જોઈએ? અમે અહીં છીએ.",
    callCta: "કૉલ કરો",
    whatsappHelpCta: "WhatsApp પર મદદ મેળવો",
    waMyPdf: "વકિલી આણિ કાયદે — મારી PDF",
    waLinkNote: "આ link ફક્ત મારા માટે છે. આ message save કરો.",
    waLinkNoteExpire: "આ link ફક્ત મારા માટે છે. આ message save કરો — link expire થાય તે પહેલાં.",
    waHelpRequest: "નમસ્તે 🙏 વકિલી આણિ કાયદે ટીમ,\nમારે મારી પુસ્તકો ડાઉનલોડ કરવામાં મદદ જોઈએ છે. કૃપા કરીને માર્ગદર્શન કરો.",
    waPaidNoBook: "નમસ્તે 🙏 વકિલી આણિ કાયદે ટીમ,\nમેં પુસ્તકના પૈસા ભર્યા છે, પણ તે મારા ખાતામાં દેખાતું નથી.\n📱 મારો નંબર: {phone}\nકૃપા કરીને તપાસો.",
  },
  BENGALI: {
    techError: "একটি প্রযুক্তিগত সমস্যা হয়েছে। অনুগ্রহ করে কিছুক্ষণ পরে চেষ্টা করুন।",
    rateLimited: "অনেকবার চেষ্টা করা হয়েছে। অনুগ্রহ করে কিছুক্ষণ পরে চেষ্টা করুন।",
    somethingWrong: "কিছু একটা ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    booksFound: "{n}টি বই পাওয়া গেছে!",
    purchaseSuccessToast: "ক্রয় সফল! আপনার বই নিচে রয়েছে।",
    paymentProcessingToast: "পেমেন্ট প্রক্রিয়াধীন... অনুগ্রহ করে অপেক্ষা করুন।",
    purchaseReadyToast: "ক্রয় সফল! আপনার বই প্রস্তুত।",
    downloadStarted: "ডাউনলোড শুরু হয়েছে! 📥",
    bookReady: "আপনার বই প্রস্তুত — এখনই ডাউনলোড করুন",
    waDelivered: "আপনার WhatsApp-এ PDF পাঠানো হয়েছে। না পেলে নিচের বোতাম ব্যবহার করুন।",
    downloading: "ডাউনলোড হচ্ছে...",
    linkPreparing: "আপনার লিঙ্ক প্রস্তুত হচ্ছে...",
    libraryTitle: "আপনার ডিজিটাল লাইব্রেরি",
    librarySub: "WhatsApp নম্বর লিখুন — আপনার বই সঙ্গে সঙ্গে পান",
    phonePlaceholder: "WhatsApp নম্বর...",
    searchBtn: "খুঁজুন",
    searchYourBooks: "আপনার বই খুঁজুন",
    searchPrompt: "উপরে আপনার WhatsApp নম্বর লিখে \"খুঁজুন\" চাপুন",
    booksCount: "{n}টি বই",
    noBooksFound: "কোনো বই পাওয়া যায়নি",
    checkNumber: "নম্বরটি যাচাই করুন বা সাপোর্টের সাথে যোগাযোগ করুন।",
    paidButNoBook: "টাকা দিয়েছেন কিন্তু বই পাননি?",
    suggestedForYou: "আপনার জন্য প্রস্তাবিত",
    needHelp: "সাহায্য দরকার? আমরা এখানে আছি।",
    callCta: "কল করুন",
    whatsappHelpCta: "WhatsApp-এ সাহায্য নিন",
    waMyPdf: "ভাকিলি আনি কায়দে — আমার PDF",
    waLinkNote: "এই link শুধু আমার জন্য। এই message save করুন।",
    waLinkNoteExpire: "এই link শুধু আমার জন্য। এই message save করুন — link expire হওয়ার আগে।",
    waHelpRequest: "নমস্কার 🙏 ভাকিলি আনি কায়দে টিম,\nআমার বই ডাউনলোড করতে সাহায্য দরকার। অনুগ্রহ করে গাইড করুন।",
    waPaidNoBook: "নমস্কার 🙏 ভাকিলি আনি কায়দে টিম,\nআমি বইয়ের টাকা দিয়েছি, কিন্তু তা আমার অ্যাকাউন্টে দেখাচ্ছে না।\n📱 আমার নম্বর: {phone}\nঅনুগ্রহ করে যাচাই করুন।",
  },
};
